routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DetailKriteriaController;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\NormalisasiController;
use App\Http\Controllers\PemohonController;
use App\Http\Controllers\PendukungController;
use App\Http\Controllers\PenilaianController;
use App\Http\Controllers\PerhitunganController;
use App\Http\Controllers\RankingController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::middleware(['web', 'auth'])->group(function(){
    Route::get('dashboard', [DashboardController::class, 'index']);
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('detail-kriteria', DetailKriteriaController::class);
    Route::resource('pemohon', PemohonController::class);
    Route::resource('pendukung', PendukungController::class);
    Route::resource('penilaian', PenilaianController::class);
    Route::resource('user', UserController::class);
    Route::post('hitung', [PerhitunganController::class, 'hitung'])->name('hitung');
    Route::get('normalisasi', [NormalisasiController::class, 'index'])->name('normalisasi.index');
    Route::get('hasil', [RankingController::class, 'hasil'])->name('hasil.index');
    Route::get('print', [RankingController::class, 'print'])->name('ranking.print');

    Route::get('laporan-kredit', [RankingController::class, 'laporanKredit'])->name('laporan.kredit');
});

app/Models/Pemohon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pemohon extends Model
{
    use HasFactory;

    protected $table = 'pemohon';

    protected $fillable = [
        'nama',
        'tmpt_lhr',
        'tgl_lhr',
        'alamat',
        'j_kel',
        'status_nikah',
        'email',
        'no_telp',
        'platform_pinjaman',
        'user_id'
    ];

    public function pendukung()
    {
        return $this->hasOne('App\Models\Pendukung');
    }

    public static function getDefaultValues()
    {
        return [
            'nama' => '',
            'tmpt_lhr' => '',
            'tgl_lhr' => '',
            'alamat' => '',
            'j_kel' => '',
            'status_nikah' => '',
            'email' => '',
            'no_telp' => '',
            'platform_pinjaman' => '',
        ];
    }

    public function getStatusNikah()
    {
        if($this->status_nikah === 0) {
            return "Belum Menikah";
        } else {
            return "Menikah";
        }
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }
}

app/Http/Controllers/PemohonController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pemohon;
use App\Models\Pendukung;
use Illuminate\Http\Request;

class PemohonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->get('dari') == null){
            $data['pemohon'] = Pemohon::all();
        } else {
            $data['pemohon'] = Pemohon::join('pendukung', 'pendukung.pemohon_id', 'pemohon.id')
                                ->whereBetween('tgl_pengajuan', [request()->get('dari'), request()->get('sampai')])
                                ->get();
        }
        return view('pemohon.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(auth()->user()->level == 2){
            return redirect('dashboard')->with('warning', 'Anda tidak memiliki akses');
        }
        $data['pemohon'] = Pemohon::getDefaultValues();
        $data['pendukung'] = Pendukung::getDefaultValues();
        return view('pemohon.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama' => 'required',
            'tmpt_lhr' => 'required',
            'tgl_lhr' => 'required',
            'alamat' => 'required',
            'j_kel' => 'required',
            'status_nikah' => 'required',
            'email' => 'required',
            'no_telp' => 'required',
            'platform_pinjaman' => 'required',
            'status_bi_checking' => 'required',
            'jangka_waktu' => 'required',
            'jenis_bunga' => 'required',
            'bunga' => 'required',
            'angsuran' => 'required',
            'penghasilan' => 'required',
            'tgl_pengajuan' => 'required',
            'jumlah_keluarga' => 'required',
            'jaminan' => 'required',
            'kepemilikan_rumah' => 'required',
        ]);
        $input = $request->toArray();
        $input['user_id'] = auth()->user()->id;
        $pemohon = Pemohon::create($input);
        Pendukung::create([
            'pemohon_id' => $pemohon->id,
            'status_bi_checking' => $input['status_bi_checking'],
            'jangka_waktu' => $input['jangka_waktu'],
            'jenis_bunga' => $input['jenis_bunga'],
            'bunga' => $input['bunga'],
            'angsuran' => $input['angsuran'],
            'penghasilan' => $input['penghasilan'],
            'tgl_pengajuan' => $input['tgl_pengajuan'],
            'jumlah_keluarga' => $input['jumlah_keluarga'],
            'jaminan' => $input['jaminan'],
            'kepemilikan_rumah' => $input['kepemilikan_rumah'],
        ]);
        return redirect()->route('pemohon.index')->with('success', 'Berhasil menambah data pemohon');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\pemohon  $pemohon
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\pemohon  $pemohon
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(auth()->user()->level == 2){
            return redirect('dashboard')->with('warning', 'Anda tidak memiliki akses');
        }
        $data['pemohon'] = Pemohon::findOrFail($id);
        $data['pendukung'] = Pendukung::where('pemohon_id', $id)->first();
        return view('pemohon.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\pemohon  $pemohon
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nama' => 'required',
            'tmpt_lhr' => 'required',
            'tgl_lhr' => 'required',
            'alamat' => 'required',
            'j_kel' => 'required',
            'status_nikah' => 'required',
            'email' => 'required',
            'no_telp' => 'required',
            'platform_pinjaman' => 'required',
            'status_bi_checking' => 'required',
            'jangka_waktu' => 'required',
            'jenis_bunga' => 'required',
            'bunga' => 'required',
            'angsuran' => 'required',
            'penghasilan' => 'required',
            'tgl_pengajuan' => 'required',
            'jumlah_keluarga' => 'required',
            'jaminan' => 'required',
            'kepemilikan_rumah' => 'required',
        ]);
        $input = $request->toArray();
        $input['user_id'] = auth()->user()->id;
        Pemohon::findOrfail($id)->update($input);
        Pendukung::updateOrCreate(
            ['pemohon_id' => $id],
            [
                'status_bi_checking' => $input['status_bi_checking'],
                'jangka_waktu' => $input['jangka_waktu'],
                'jenis_bunga' => $input['jenis_bunga'],
                'bunga' => $input['bunga'],
                'angsuran' => $input['angsuran'],
                'penghasilan' => $input['penghasilan'],
                'tgl_pengajuan' => $input['tgl_pengajuan'],
                'jumlah_keluarga' => $input['jumlah_keluarga'],
                'jaminan' => $input['jaminan'],
                'kepemilikan_rumah' => $input['kepemilikan_rumah'],
            ]
        );
        return redirect()->route('pemohon.index')->with('success', 'Berhasil mengubah data pemohon');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\pemohon  $pemohon
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Pemohon::findOrfail($id)->delete();
        return redirect()->route('pemohon.index')->with('success', 'Berhasil menghapus data pemohon');
    }
}

resources/views/pemohon/index.blade.php
@extends('layouts.app')

@section('title', 'Pemohon')

@section('content')
    <div class="header bg-gray-dark pb-5">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Pemohon</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Filter Tanggal Pengajuan</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="" method="get">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="">Dari</label>
                                    <input type="text" class="form-control datepicker" name="dari" value="{{ request()->get('dari') }}">
                                </div>
                                <div class="col-md-6">
                                    <label for="">Sampai</label>
                                    <input type="text" class="form-control datepicker" name="sampai" value="{{ request()->get('sampai') }}">
                                </div>
                                <div class="col-md-12 text-right mt-3">
                                    <input type="submit" value="Cari" class="btn btn-info">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Data Pemohon / Alternatif</h3>
                            </div>
                            @if(auth()->user()->level == 1 || auth()->user()->level == 3)
                                <div class="col text-right">
                                    <a href="{{ route('pemohon.create') }}" class="btn btn-sm btn-primary">Tambah</a>
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>Kode</th>
                                    <th>Nama</th>
                                    <th>TTL</th>
                                    <th>Tgl. Pengajuan</th>
                                    <th>Platform Pinjaman</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($pemohon as $row)
                                    <tr>
                                        <td>A{{ $row->id }}</td>
                                        <td>{{ $row->nama }}</td>
                                        <td>{{ $row->tmpt_lhr . ', ' . $row->tgl_lhr }}</td>
                                        <td>{{ $row->pendukung->tgl_pengajuan ?? 'N/A' }}</td>
                                        <td>{{ 'Rp.' . number_format($row->platform_pinjaman) }}</td>
                                        <td>
                                            <form action="{{ route('pemohon.destroy', $row->id) }}" method="post">
                                                @csrf
                                                @method('delete')
                                                <a href="{{ route('pendukung.show', $row->id) }}" class="btn btn-sm btn-success text-white">Detail & Pendukung</a>
                                                @if(auth()->user()->level == 1 || auth()->user()->level == 3)
                                                    <a href="{{ route('pemohon.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                                    <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                                @endif
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection