routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DetailKriteriaController;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\NormalisasiController;
use App\Http\Controllers\PemohonController;
use App\Http\Controllers\PendukungController;
use App\Http\Controllers\PenilaianController;
use App\Http\Controllers\PerhitunganController;
use App\Http\Controllers\RankingController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::middleware(['web', 'auth'])->group(function(){
    Route::get('dashboard', [DashboardController::class, 'index']);
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('detail-kriteria', DetailKriteriaController::class);
    Route::resource('pemohon', PemohonController::class);
    Route::resource('pendukung', PendukungController::class);
    Route::resource('penilaian', PenilaianController::class);
    Route::resource('user', UserController::class);
    Route::post('hitung', [PerhitunganController::class, 'hitung'])->name('hitung');
    Route::get('normalisasi', [NormalisasiController::class, 'index'])->name('normalisasi.index');
    Route::get('hasil', [RankingController::class, 'hasil'])->name('hasil.index');
    Route::get('print', [RankingController::class, 'print'])->name('ranking.print');

    Route::get('laporan-kredit', [RankingController::class, 'laporanKredit'])->name('laporan.kredit');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'nama',
        'email',
        'password',
        'alamat',
        'no_telp',
        'level', // 1. CS, 2. Account Officer, 3. Admin
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setPasswordAttribute($value)
    {
        return $this->attributes['password'] = Hash::make($value);
    }

    public static function getDefaultValues()
    {
        return [
            'nama' => '',
            'email' => '',
            'password' => '',
            'alamat' => '',
            'no_telp' => '',
            'level' => '',
        ];
    }

    public function getLevel()
    {
        if ($this->level === 1) {
            return 'Customer Service';
        }

        if ($this->level === 2) {
            return 'Account Officer';
        }

        if ($this->level === 3) {
            return 'Admin';
        }

        if ($this->level == 4) {
            return 'Direksi';
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['user'] = User::all();
        return view('user.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(auth()->user()->level !== 3) {
            return redirect('dashboard')->with('warning', 'Anda tidak memiliki akses');
        }
        $data['user'] = User::getDefaultValues();

        return view('user.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'email' => 'required|unique:users,email',
            'nama' => 'required',
            'level'=> 'required',
            'alamat' => 'required',
            'no_telp' => 'required',
            'password' => 'required',
        ]);

        User::create($request->toArray());
        return redirect()->route('user.index')->with('success', 'Berhasil menambah data user');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\users  $users
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(auth()->user()->level !== 3) {
            if(auth()->user()->id != $id) {
                return redirect('dashboard')->with('warning', 'Anda tidak memiliki akses');
            }
        }
        $data['user'] = User::findOrFail($id);
        return view('user.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\users  $users
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'email' => 'required',
            'nama' => 'required',
            'level'=> 'required',
            'alamat' => 'required',
            'no_telp' => 'required',
        ]);
        $input = $request->toArray();
        if(empty($input['password'])){
            unset($input['password']);
        }
        User::findOrfail($id)->update($input);
        return redirect()->route('user.index')->with('success', 'Berhasil mengubah data user');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\users  $users
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::findOrfail($id)->delete();
        return redirect()->route('user.index')->with('success', 'Berhasil menghapus data user');
    }
}

resources/views/user/form.blade.php
@extends('layouts.app')

@section('title', 'Form user')

@section('content')
    <div class="header bg-gray-dark pb-5">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Users</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                  <div class="row align-items-center">
                    <div class="col-12">
                      <h3 class="mb-0">Form User</h3>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <form action="{{ (!isset($user['id'])) ? route('user.store') : route('user.update', $user['id']) }}" method="post">
                        @csrf
                        @isset($user['id'])
                            {{ method_field('PUT')}}
                        @endisset
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Nama user</label>
                                        <input type="text" class="form-control" name="nama" placeholder="" value="{{ old('nama', $user['nama']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input type="text" class="form-control" name="email" placeholder="" value="{{ old('email', $user['email']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input type="password" class="form-control" name="password" placeholder="">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Level</label>
                                        @if(auth()->user()->level === 3)
                                        <select name="level" class="form-control">
                                            <option value="1" {{ old('level', $user['level']) == "1" ? 'selected' : '' }}>Customer Service</option>
                                            <option value="2" {{ old('level', $user['level']) == "2" ? 'selected' : '' }}>Account Officer</option>
                                            <option value="3" {{ old('level', $user['level']) == "3" ? 'selected' : '' }}>Admin</option>
                                            <option value="4" {{ old('level', $user['level']) == "4" ? 'selected' : '' }}>Direksi</option>
                                        </select>
                                        @else
                                            <input type="text" name="" class="form-control" value="{{ auth()->user()->getLevel() }}" readonly>
                                            <input type="hidden" name="level" value="{{ auth()->user()->level }}">
                                        @endif
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Alamat</label>
                                        <textarea class="form-control" name="alamat" placeholder="">{{ old('alamat', $user['alamat']) }}</textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>No. Telp</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text" id="basic">+62</span>
                                            </div>
                                            <input type="number" name="no_telp" value="{{ old('no_telp', $user['no_telp']) }}" class="form-control" placeholder="" aria-label="no_telp" aria-describedby="basic">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group text-right">
                                        <input type="submit" value="Simpan" class="btn btn-success">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
              </div>
        </div>
    </div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('title', 'User')

@section('content')
    <div class="header bg-gray-dark pb-5">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Users</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Data Users</h3>
                            </div>
                            @if(auth()->user()->level === 3)
                            <div class="col text-right">
                                <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary">Tambah</a>
                            </div>
                            @endif
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Email</th>
                                    <th>Level</th>
                                    <th>Alamat</th>
                                    <th>No. Telp</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($user as $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $row->nama }}</td>
                                        <td>{{ $row->email }}</td>
                                        <td>{!! $row->getLevel() !!}</td>
                                        <td>{{ $row->alamat }}</td>
                                        <td>{{ $row->no_telp }}</td>
                                        <td>
                                            @if(auth()->user()->level == 3)
                                                <form action="{{ route('user.destroy', $row->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <a href="{{ route('user.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                                    @if($row->id != auth()->user()->id)
                                                        <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                                    @endif
                                                </form>
                                            @else
                                                @if($row->id == auth()->user()->id)
                                                    <a href="{{ route('user.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                                @endif
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection