routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DetailKriteriaController;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\NormalisasiController;
use App\Http\Controllers\PemohonController;
use App\Http\Controllers\PendukungController;
use App\Http\Controllers\PenilaianController;
use App\Http\Controllers\PerhitunganController;
use App\Http\Controllers\RankingController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::middleware(['web', 'auth'])->group(function(){
    Route::get('dashboard', [DashboardController::class, 'index']);
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('detail-kriteria', DetailKriteriaController::class);
    Route::resource('pemohon', PemohonController::class);
    Route::resource('pendukung', PendukungController::class);
    Route::resource('penilaian', PenilaianController::class);
    Route::resource('user', UserController::class);
    Route::post('hitung', [PerhitunganController::class, 'hitung'])->name('hitung');
    Route::get('normalisasi', [NormalisasiController::class, 'index'])->name('normalisasi.index');
    Route::get('hasil', [RankingController::class, 'hasil'])->name('hasil.index');
    Route::get('print', [RankingController::class, 'print'])->name('ranking.print');

    Route::get('laporan-kredit', [RankingController::class, 'laporanKredit'])->name('laporan.kredit');
});

app/Models/Penilaian.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Penilaian extends Model
{
    use HasFactory;

    protected $table = 'penilaian';

    protected $fillable = [
        'pemohon_id',
        'detail_kriteria_id',
        'user_id'
    ];

    public static function getDefaultValues()
    {
        return [
            'pemohon_id' => '',
            'detail_kriteria_id' => ''
        ];
    }

    public function detailKriteria()
    {
        return $this->belongsTo('App\Models\DetailKriteria');
    }

    public function scopeOrderByKodeKriteria($query)
    {
        return $query->join('detail_kriteria', 'detail_kriteria.id', 'penilaian.detail_kriteria_id')
                        ->join('kriteria', 'kriteria.id', 'detail_kriteria.kriteria_id')
                        ->orderBy('kode', 'asc');
    }

    public function findMaxNumber(array $detail_kriteria_ids)
    {

    }
}

app/Http/Controllers/PenilaianController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kriteria;
use App\Models\Pemohon;
use App\Models\Penilaian;
use App\Models\Perhitungan;
use Illuminate\Http\Request;

class PenilaianController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(auth()->user()->level == 1){
            return redirect('dashboard')->with('warning', 'Anda tidak memiliki akses');
        }
        $penilaian = Penilaian::select('pemohon_id', 'detail_kriteria_id', 'kode')
                                ->orderByKodeKriteria()
                                ->get();
        $penilaian = $penilaian->groupBy('pemohon_id');
        $penilaian = $penilaian->sort();
        $penilaian = $penilaian->all();
        $data['penilaian'] = $penilaian;
        $data['kriteria'] = Kriteria::orderBy('kode')->get();
        $dataPerhitungan = Perhitungan::with('pemohon')->with('kriteria')->orderBy('pemohon_id', 'asc')->orderBy('kriteria_id', 'asc')->get();
        $data['perhitungan'] = $dataPerhitungan->groupBy('pemohon_id');
        return view('penilaian.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(auth()->user()->level == 1){
            return redirect('dashboard')->with('warning', 'Anda tidak memiliki akses');
        }
        $filled = Penilaian::select('pemohon_id')->distinct()->get()->pluck('pemohon_id')->all();
        $data['pemohon'] = Pemohon::whereNotIn('id', $filled)->get();
        $data['kriteria'] = Kriteria::orderBy('kode', 'asc')->get();
        $data['penilaian'] = Penilaian::getDefaultValues();
        $data['type'] = 'create';
        return view('penilaian.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'pemohon_id' => 'required',
        ]);
        foreach($request['detail_kriteria_ids'] as $detail_kriteria_id) {
            Penilaian::create([
                'pemohon_id' => $request['pemohon_id'],
                'detail_kriteria_id' => $detail_kriteria_id,
                'user_id' => auth()->user()->id,
            ]);
        }

        return redirect()->route('penilaian.index')->with('success', 'Berhasil menyimpan penilaian');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($pemohon_id)
    {
        if(auth()->user()->level == 1){
            return redirect('dashboard')->with('warning', 'Anda tidak memiliki akses');
        }
        $penilaian = Penilaian::select('pemohon_id', 'detail_kriteria_id', 'kode', 'detail_kriteria.keterangan as ket', 'user_id')
                    ->orderByKodeKriteria()
                    ->where('pemohon_id', $pemohon_id)
                    ->get();
        $data['penilaian'] = $penilaian->groupBy('kode')->all();
        $data['pemohon'] = Pemohon::findOrFail($pemohon_id);

        return view('penilaian.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($pemohon_id)
    {
        if(auth()->user()->level == 1){
            return redirect('dashboard')->with('warning', 'Anda tidak memiliki akses');
        }
        $penilaian = Penilaian::select('pemohon_id', 'detail_kriteria_id', 'kode')
                    ->orderByKodeKriteria()
                    ->where('pemohon_id', $pemohon_id)
                    ->get();
        $data['penilaian'] = $penilaian->groupBy('kode')->all();
        $data['pemohon'] = Pemohon::findOrFail($pemohon_id);
        $data['kriteria'] = Kriteria::orderBy('kode', 'asc')->get();
        $data['type'] = 'edit';

        return view('penilaian.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $pemohon_id)
    {
        $request->validate([
            'pemohon_id' => 'required',
        ]);

        Penilaian::where('pemohon_id', $pemohon_id)->delete();

        foreach($request['detail_kriteria_ids'] as $detail_kriteria_id) {
            Penilaian::create([
                'pemohon_id' => $request['pemohon_id'],
                'detail_kriteria_id' => $detail_kriteria_id,
                'user_id' => auth()->user()->id,
            ]);
        }

        return redirect()->route('penilaian.index')->with('success', 'Berhasil mengubah penilaian');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($pemohon_id)
    {
        Penilaian::where('pemohon_id', $pemohon_id)->delete();
        return redirect()->back()->with('success', 'Berhasil menghapus penilaian');
    }
}

resources/views/penilaian/form.blade.php
@extends('layouts.app')

@section('title', 'Form Penilaian')

@section('content')
    <div class="header bg-gray-dark pb-5">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Form Penilaian</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid mt--5">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                  <div class="row align-items-center">
                    <div class="col-12">
                      <h3 class="mb-0">Form Penilaian Pemohon / Alternatif</h3>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <form action="{{ ($type == 'create') ? route('penilaian.store') : route('penilaian.update', $pemohon['id']) }}" method="post">
                        @csrf
                        @if($type != 'create')
                            {{ method_field('PUT')}}
                        @endif
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Nama pemohon</label>
                                        @if($type == 'create')
                                            <select name="pemohon_id" class="form-control select2" required>
                                                <option value="">- Pilih -</option>
                                                @foreach($pemohon as $option)
                                                    <option value="{{ $option->id }}">{{ $option->nama }}</option>
                                                @endforeach
                                            </select>
                                        @else
                                            <input type="text" class="form-control" value="{{ $pemohon->nama }}" readonly>
                                            <input type="hidden" name="pemohon_id" value="{{ $pemohon->id }}">
                                        @endif
                                    </div>
                                </div>
                                @foreach($kriteria as $form)
                                    <div class="col-lg-12">
                                        <div class="form-group">
                                            <label>{{ $form->kode . ' - ' . $form->nama }}</label>
                                            <select name="detail_kriteria_ids[]" id="" class="form-control" required>
                                                @foreach($form->detail_kriteria()->orderBy('skor', 'asc')->get() as $option)
                                                    <option value="{{ $option->id }}" {{ ($penilaian[$form->kode][0]->detail_kriteria_id ?? '') === $option->id ? 'selected' : ''  }}>{{ $option->keterangan }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                @endforeach
                                <div class="col-md-12 text-right">
                                    <input type="submit" value="Simpan" class="btn btn-success">
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/penilaian/index.blade.php
@extends('layouts.app')

@section('title', 'Penilaian')

@section('content')
    <div class="header bg-gray-dark pb-5">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Penilaian</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Data Pemohon / Alternatif + Penilaian</h3>
                            </div>
                            <div class="col text-right">
                                <a href="{{ route('penilaian.create') }}" class="btn btn-sm btn-primary">Tambah</a>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>#</th>
                                    <th>Pemohon / Alternatif</th>
                                    @foreach($kriteria as $th)
                                        <th>{{ $th->kode }}</th>
                                    @endforeach
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($penilaian as $key => $row)
                                <?php
                                    $pemohon = getDetailAlternatif($key);
                                ?>
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ 'A'.$pemohon->id . ' - ' . $pemohon->nama }}</td>
                                    @foreach($row as $value)
                                        <td>{{ $value->detailKriteria->keterangan }}</td>
                                    @endforeach
                                    <td>
                                        <form action="{{ route('penilaian.destroy', $key) }}" method="post">
                                            @csrf
                                            @method('delete')
                                            <a href="{{ route('penilaian.show', $key) }}" class="btn btn-sm btn-info"><i class="fa fa-eye"></i></a>
                                            <a href="{{ route('penilaian.edit', $key) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                            <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-end">
            <div class="col-md-6">
                <form action="{{ route('hitung') }}" method="post">
                    @csrf
                    <button type="submit" class="btn btn-success btn-block" onclick="return confirm('Apakah anda yakin untuk mulai melakukan perhitungan?')"><i class="fa fa-calculator"></i> Hitung</button>
                </form>
            </div>
        </div>
    </div>

    <div class="container-fluid mt-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Matrix Keputusan</h3>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>#</th>
                                    <th>Pemohon / Alternatif</th>
                                    @foreach($kriteria as $th)
                                        <th>{{ $th->kode }}</th>
                                    @endforeach
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($perhitungan as $key => $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ 'A'.$row[0]->pemohon->id . ' - ' . $row[0]->pemohon->nama }}</td>
                                        @foreach($row as $value)
                                            <td>{{ $value['matrix'] }}</td>
                                        @endforeach
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Tabel Normalisasi</h3>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>#</th>
                                    <th>Pemohon / Alternatif</th>
                                    @foreach($kriteria as $th)
                                        <th>{{ $th->kode }}</th>
                                    @endforeach
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($perhitungan as $key => $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ 'A'.$row[0]->pemohon->id . ' - ' . $row[0]->pemohon->nama }}</td>
                                        @foreach($row as $value)
                                            <td>{{ $value['normalisasi'] }}</td>
                                        @endforeach
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/penilaian/show.blade.php
@extends('layouts.app')

@section('title', 'Penilaian')

@section('content')
    <div class="header bg-gray-dark pb-5">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Detail Penilaian</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Penilaian {{ $pemohon->nama }}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <tr>
                                    <td>Nama</td>
                                    <td>:</td>
                                    <td>{{ $pemohon->nama }}</td>
                                </tr>
                                @foreach($penilaian as $key => $value)
                                    <tr>
                                        <td>{{ $key }}</td>
                                        <td>:</td>
                                        <td>{{ $value[0]->ket ?? '' }}</td>
                                    </tr>
                                @endforeach
                                <tr>
                                    <td>Ditambahkan oleh</td>
                                    <td>:</td>
                                    <td>{{ getUser($value[0]->user_id)->nama ?? '' }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection