routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DetailKriteriaController;
use App\Http\Controllers\KriteriaController;
use App\Http\Controllers\NormalisasiController;
use App\Http\Controllers\PemohonController;
use App\Http\Controllers\PendukungController;
use App\Http\Controllers\PenilaianController;
use App\Http\Controllers\PerhitunganController;
use App\Http\Controllers\RankingController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::middleware(['web', 'auth'])->group(function(){
    Route::get('dashboard', [DashboardController::class, 'index']);
    Route::resource('kriteria', KriteriaController::class);
    Route::resource('detail-kriteria', DetailKriteriaController::class);
    Route::resource('pemohon', PemohonController::class);
    Route::resource('pendukung', PendukungController::class);
    Route::resource('penilaian', PenilaianController::class);
    Route::resource('user', UserController::class);
    Route::post('hitung', [PerhitunganController::class, 'hitung'])->name('hitung');
    Route::get('normalisasi', [NormalisasiController::class, 'index'])->name('normalisasi.index');
    Route::get('hasil', [RankingController::class, 'hasil'])->name('hasil.index');
    Route::get('print', [RankingController::class, 'print'])->name('ranking.print');

    Route::get('laporan-kredit', [RankingController::class, 'laporanKredit'])->name('laporan.kredit');
});

app/Models/Kriteria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Kriteria extends Model
{
    use HasFactory;

    protected $table = 'kriteria';

    protected $fillable = [
        'kode',
        'nama',
        'jenis_kriteria',
        'bobot',
        'keterangan',
    ];

    public function setKodeAttribute($value)
    {
        $this->attributes['kode'] = Str::upper($value);
    }

    public static function getDefaultValues()
    {
        return [
            'kode' => '',
            'nama' => '',
            'jenis_kriteria' => '',
            'bobot' => '',
            'keterangan' => ''
        ];
    }

    public function getJenisKriteria()
    {
        if($this->jenis_kriteria == 'benefit') {
            return '<span class="badge badge-primary">Benefit</span>';
        } else {
            return '<span class="badge badge-warning">Cost</span>';
        }
    }

    public function detail_kriteria()
    {
        return $this->hasMany('App\Models\DetailKriteria');
    }
}

app/Http/Controllers/KriteriaController.php
<?php

namespace App\Http\Controllers;

use App\Models\DetailKriteria;
use App\Models\Kriteria;
use Illuminate\Http\Request;

class KriteriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(auth()->user()->level == 1){
            return redirect('dashboard')->with('warning', 'Anda tidak memiliki akses');
        }

        $data['kriteria'] = Kriteria::all();
        return view('kriteria.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(auth()->user()->level == 1){
            return redirect('dashboard')->with('warning', 'Anda tidak memiliki akses');
        }
        $data['kriteria'] = Kriteria::getDefaultValues();

        return view('kriteria.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'kode' => 'required|unique:kriteria,nama',
            'nama' => 'required|unique:kriteria,nama',
            'jenis_kriteria'=> 'required',
            'bobot' => 'required',
        ]);

        Kriteria::create($request->toArray());
        return redirect()->route('kriteria.index')->with('success', 'Berhasil menambah data kriteria');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\kriteria  $kriteria
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(auth()->user()->level == 1){
            return redirect('dashboard')->with('warning', 'Anda tidak memiliki akses');
        }
        $data['kriteria'] = Kriteria::find($id);
        $data['table_detail_kriteria'] = DetailKriteria::where('kriteria_id', $id)->orderBy('skor', 'asc')->get();
        $data['detail_kriteria'] = DetailKriteria::getDefaultValues();
        return view('kriteria.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\kriteria  $kriteria
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['kriteria'] = Kriteria::findOrFail($id);
        return view('kriteria.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\kriteria  $kriteria
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'kode' => 'required',
            'nama' => 'required',
            'jenis_kriteria'=> 'required',
            'bobot' => 'required',
        ]);

        Kriteria::findOrfail($id)->update($request->toArray());
        return redirect()->route('kriteria.index')->with('success', 'Berhasil mengubah data kriteria');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\kriteria  $kriteria
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Kriteria::findOrfail($id)->delete();
        return redirect()->route('kriteria.index')->with('success', 'Berhasil menghapus data kriteria');
    }
}

resources/views/kriteria/form.blade.php
@extends('layouts.app')

@section('title', 'Form Kriteria')

@section('content')
    <div class="header bg-gray-dark pb-5">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Kriteria</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                  <div class="row align-items-center">
                    <div class="col-12">
                      <h3 class="mb-0">Form kriteria</h3>
                    </div>
                  </div>
                </div>
                <div class="card-body">
                    <form action="{{ (!isset($kriteria['id'])) ? route('kriteria.store') : route('kriteria.update', $kriteria['id']) }}" method="post">
                        @csrf
                        @isset($kriteria['id'])
                            {{ method_field('PUT')}}
                        @endisset
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Kode</label>
                                        <input type="text" class="form-control" name="kode" placeholder="Contoh: C1" value="{{ old('kode', $kriteria['kode']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Nama kriteria</label>
                                        <input type="text" class="form-control" name="nama" placeholder="Contoh: Character" value="{{ old('nama', $kriteria['nama']) }}">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Jenis Kriteria</label>
                                        <select name="jenis_kriteria" class="form-control">
                                            <option value="benefit" {{ old('jenis_kriteria', $kriteria['jenis_kriteria']) == "benefit" ? 'selected' : '' }}>Benefit</option>
                                            <option value="cost" {{ old('jenis_kriteria', $kriteria['jenis_kriteria']) == "cost" ? 'selected' : '' }}>Cost</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Bobot</label>
                                        <div class="input-group mb-3">
                                            <input type="number" name="bobot" value="{{ old('bobot', $kriteria['bobot']) }}" class="form-control" placeholder="Bobot" aria-label="Bobot" aria-describedby="basic">
                                            <div class="input-group-append">
                                                <span class="input-group-text" id="basic">%</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="form-group">
                                        <label>Keterangan</label>
                                        <textarea name="keterangan" value="{{ old('keterangan', $kriteria['keterangan']) }}" class="form-control" placeholder="keterangan"></textarea>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group text-right">
                                        <input type="submit" value="Simpan" class="btn btn-success">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
              </div>
        </div>
    </div>

@endsection

resources/views/kriteria/index.blade.php
@extends('layouts.app')

@section('title', 'Kriteria')

@section('content')
    <div class="header bg-gray-dark pb-5">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Kriteria</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">Data Kriteria</h3>
                            </div>
                            <div class="col text-right">
                                <a href="{{ route('kriteria.create') }}" class="btn btn-sm btn-primary">Tambah</a>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>No</th>
                                    <th>Kode</th>
                                    <th>Nama</th>
                                    <th>Jenis</th>
                                    <th>Bobot</th>
                                    <th>Keterangan</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($kriteria as $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $row->kode }}</td>
                                        <td>{{ $row->nama }}</td>
                                        <td>{!! $row->getJenisKriteria() !!}</td>
                                        <td>{{ $row->bobot }}%</td>
                                        <td>{{ $row->keterangan }}</td>
                                        <td>
                                            <form action="{{ route('kriteria.destroy', $row->id) }}" method="post">
                                                @csrf
                                                @method('delete')
                                                <a href="{{ route('kriteria.show', $row->id ) }}" class="btn btn-sm btn-success text-white" title="Detail Kriteria"><i class="fa fa-table"></i></a>
                                                <a href="{{ route('kriteria.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a>
                                                <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/kriteria/show.blade.php
@extends('layouts.app')

@section('title', 'Kriteria')

@section('content')
    <div class="header bg-gray-dark pb-5">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-lg-6 col-7">
                        <h6 class="h2 text-white d-inline-block mb-0">Detail Kriteria</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Page content -->
    <div class="container-fluid mt--5">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col">
                                <h3 class="mb-0">{{ $kriteria->kode . ' - ' . $kriteria->nama }}</h3>
                            </div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th>No</th>
                                    <th>Keterangan</th>
                                    <th>Skor</th>
                                    <th>Hapus</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($table_detail_kriteria ?? [] as $row)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $row->keterangan }}</td>
                                        <td>{{ $row->skor }}</td>
                                        <td>
                                            <form action="{{ route('detail-kriteria.destroy', $row->id) }}" method="post">
                                                @csrf
                                                @method('delete')
                                                {{-- <a href="{{ route('detail-kriteria.edit', $row->id) }}" class="btn btn-sm btn-warning text-white" title="Edit"><i class="fa fa-cog"></i></a> --}}
                                                <button type="submit" class="btn btn-danger btn-sm" title="Hapus" onclick="return confirm('Yakin untuk menghapus data?')"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>

                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                      <div class="row align-items-center">
                        <div class="col-12">
                          <h3 class="mb-0">Form {{ $kriteria->kode . ' - ' . $kriteria->nama }}</h3>
                        </div>
                      </div>
                    </div>
                    <div class="card-body">
                        <form action="{{ (!isset($detail_kriteria['id'])) ? route('detail-kriteria.store') : route('detail-kriteria.update', $detail_kriteria['id']) }}" method="post">
                            @csrf
                            @isset($detail_kriteria['id'])
                                {{ method_field('PUT')}}
                            @endisset
                            <input type="hidden" name="kriteria_id" value="{{ $kriteria->id }}">

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Keterangan</label>
                                        <textarea class="form-control" name="keterangan" rows="3">{{ old('keterangan', $detail_kriteria['keterangan']) }}</textarea>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Skor</label>
                                        <input type="text" class="form-control" name="skor" {{ old('skor', $detail_kriteria['skor']) }}>
                                    </div>
                                </div>
                                <div class="col-md-12 text-right">
                                    <input type="submit" value="Simpan" class="btn btn-success">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection